baseURL: "https://yuto02d2-e2.github.io/blog/"
title: "yuto's blog"
author: "yuto"
theme: "PaperMod"
DefaultContentLanguage: "en"
languageCode: "en-US"
googleAnalytics: G-WMX37QZ9R1

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
hasCJKLanguage: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "yuto's blog"
  author: "yuto"
  description: "en:yuto's blog site. ja:yutoのブログサイトです．"
  keywords:
    ["yuto", "Blog", "Portfolio", "Hugo", "PaperMod", "Markdown", "GithubPages"]
  images: ["images/logo.png"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  hidemeta: false
  showtoc: true
  tocopen: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: true

  label: # ヘッダーの左側にあるやつ
    text: "yuto's blog"
    icon: "images/logo.png"
    iconHeight: 40

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    subtitle: "welcome to here. take your time :)"
    imageUrl: "images/logo.png"
    imageWidth: 256
    imageHeight: 256
    # buttons:
    #   - name: "readme"
    #     url: "readme"

  # profile-modeでアイコンの下に表示される
  socialIcons:
    - name: github
      url: "https://github.com/Yuto02D2-E2/"
    - name: rss
      url: "index.xml"

  cover:
    linkFullImages: true

  # 記事のソースへのリンク
  editPost:
    URL: "https://github.com/Yuto02D2-E2/blog/tree/main/content"
    Text: "view source on github" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    includeScore: true
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content", "categories", "tags"]
    useExtendedSearch: true

  # static/からの相対パスであることに注意
  assets:
    css: "css/custom.css"
    favicon: "images/favicon.ico"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

# hugo newでeditorを指定するため
security:
  exec:
    allow:
      - ^code$

minify:
  disableXML: false
  minifyOutput: true

menu: # ヘッダーの右側にあるやつ
  main:
    - identifier: readme
      name: readme
      url: "readme"
      weight: 10
    - identifier: archives
      name: archives
      url: "archives"
      weight: 20
    - identifier: categories
      name: categories
      url: "categories"
      weight: 30
    - identifier: tags
      name: tags
      url: "tags"
      weight: 40
    - identifier: search
      name: search
      url: "search"
      weight: 50

# for search page
outputs:
  home:
    - HTML
    - RSS
    - JSON
